export interface ProductItem {
  id: number;
  productImg: string;
  alt: string;
  title: string;
  desc: string;
  rate: number;
  price: number;
  href: string;
}

export const productsData: ProductItem[] = [
  {
    id: 1,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Air m3",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 2,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 3,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 4,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 5,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Pro M3 Pro",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 6,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Air M1",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 7,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 8,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 9,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 10,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 11,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Air m3",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 12,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 13,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 14,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 15,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Pro M3 Pro",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 16,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Air M1",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 17,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 18,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 19,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 20,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
];

export const productsPopular: ProductItem[] = [
  {
    id: 1,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Air m3",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 2,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Pro M3 Pro",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 3,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Air M1",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 4,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 5,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Air m3",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 6,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Pro M3 Pro",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 7,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Macbook Air M1",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 8,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 9,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
  {
    id: 10,
    productImg: "/assets/images/products/macbook.webp",
    alt: "productA",
    title: "Lapotop ROG STRIK",
    desc: "Laptop bisa dibawa mati",
    rate: 4.3,
    price: 1000,
    href: "/products/laptop",
  },
];
